### PR TITLE
Refactor templates to decouple deployment from configmap

### PR DESCRIPTION
**Pull request by lulf**
This is a refactoring for decoupling deploymentconfig from the configmap holding the address config.

### CODE REVIEW

**Comment by grs** [comment]
Does this move all addresses to a separate config? I.e. even if the DeploymentConfiguration represents a single queue/topic?

**Comment by lulf** [comment]
@grs Yes, all addresses are moved to a separate config (except for direct addresses), and this makes it easier to handle in both address controller and configserv.

However, the separate config could be created automatically by the address controller as well. The reason it is created explicitly in the template, is so you can create queues/topics without using address controller, and have them recognized by the address controller later on the way it is done now.

But i'm having the feeling that supporting EnMasse without the address-controller is not really relevant anymore?

**Comment by grs** [comment]
I'd like to keep the ability to drive things purely from templates. It feels like a good way of enforcing some layering.

So now we will have a configmap per address, is that right? (In addition to a deployment controller for every set of brokers backing one or more of those addresses).

**Comment by lulf** [comment]
@grs Actually, there is a config map for each 'group', and it contains 'address -> settings' mapping in the data field.

**Comment by grs** [comment]
One (to me) unintended effect of the grouping syntax is that it makes the scalable queue (which I have been thinking was the more common case) more verbose. Or to put it another way, at present a group limits the ability to scale yet the syntax 'encourages' multi-address groups.

Perhaps this is not an issue as a GUI can mask the details of the syntax. Just mentioning it as it had not previously occurred to me.

**Comment by lulf** [comment]
@grs My plan was to support both syntaxes using either /v1/enmasse/addresses or /v2/enmasse/addresses for each of them. Alternatively, we can 'detect' the grouping syntax being used or not by checking if store_and_forward exists and is a boolean field, in which case it is not a group but a regular address.

**Pull request merged**
