### PR TITLE
Added MQTT frontend service, deployment and image stream

### PR DESCRIPTION
**Pull request by ppatierno**

### CODE REVIEW

**Comment by ppatierno** [comment]
I'm thinking about having MQTT in the same pod as the router. It could make sense because without the AMQP connection to the router, MQTT can't work but it's even true that if the MQTT pod is running but the AMQP router is crashed, an MQTT client can receive a CONNACK message as reply with "server unavailable" error. If MQTT is running in the same pod, the client can't connect because no one is listening on the port 1883.
At same time it could make sense having them scaling separately, i.e. more MQTT endpoint leveraging on few router replicas.

@grs what do you think about that ?

**Comment by grs** [comment]
I would leave them as separate pods for now I think, since they may want to be scaled separately as you point out. It would be easy to offer a template in the future that combined them if there was interest for it.

**Comment by lulf** [comment]
@grs @ppatierno 

Paolo brought up an interesting question: how to expose the mqtt service. IMO the ideal and most intuitive approach would be that 'mqtt' was an additional port on the 'messaging' service. 

The problem is that a service can only match 1 label selector, meaning that the router and mqtt frontend would have to run in the same pod for that to work.

An alternative is to just create an 'mqtt' service, but then the messaging service should be called 'amqp' for consistency.

Another alternative is to skip the selector on the service and implement the 'endpoints' creation ourselves, which is possible according to http://kubernetes.io/docs/user-guide/services/#services-without-selectors though it seems a bit complex.

Thoughts?

**Comment by grs** [comment]
I don't see it as a huge problem having 'mqtt' as a separate service. I don't object to renaming 'messaging', but I don't see it as a problem either. At present amqp is somewhat privileged which the current naming reflects.

**Comment by lulf** [comment]
@grs I agree, it is not a huge problem and I'm not opposed to keeping the current state. But I hope we can improve this some day, because I think services in OpenShift should be more abstract concepts like 'database' or 'frontend'. Having an 'amqp', and 'mqtt' service feels as wrong as having a service named 'http' , and 'clutters' the UI with a lot of services. I'll put this quite far down on the list of things to worry about :)

**Comment by ppatierno** [comment]
My concern is that even if we have different services as today (messaging for AMQP and mqtt-frontend for MQTT) we should have, of course, only one "access point" for the users/clients but for different ports (5672 and 1883). Today with two different services I have to use the cluster IP of mqtt-frontend that is different from the cluster IP of messaging.

**Pull request merged**
